/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ConnectorInterface } from "./ConnectorInterface";

export class ConnectorInterfaceFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ConnectorInterface {
    return new Contract(address, _abi, signerOrProvider) as ConnectorInterface;
  }
}

const _abi = [
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string"
      }
    ],
    stateMutability: "pure",
    type: "function"
  }
];
