/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ConnectorsInterface } from "./ConnectorsInterface";

export class ConnectorsInterfaceFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ConnectorsInterface {
    return new Contract(address, _abi, signerOrProvider) as ConnectorsInterface;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "logicAddr",
        type: "address[]"
      }
    ],
    name: "isConnector",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "logicAddr",
        type: "address[]"
      }
    ],
    name: "isStaticConnector",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
