/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ConnectorInterfaceInterface extends Interface {
  functions: {
    name: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class ConnectorInterface extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ConnectorInterface;
  attach(addressOrName: string): ConnectorInterface;
  deployed(): Promise<ConnectorInterface>;

  on(event: EventFilter | string, listener: Listener): ConnectorInterface;
  once(event: EventFilter | string, listener: Listener): ConnectorInterface;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ConnectorInterface;
  removeAllListeners(eventName: EventFilter | string): ConnectorInterface;
  removeListener(eventName: any, listener: Listener): ConnectorInterface;

  interface: ConnectorInterfaceInterface;

  functions: {
    name(overrides?: TransactionOverrides): Promise<string>;

    "name()"(overrides?: TransactionOverrides): Promise<string>;
  };

  name(overrides?: TransactionOverrides): Promise<string>;

  "name()"(overrides?: TransactionOverrides): Promise<string>;

  filters: {};

  estimate: {
    name(overrides?: TransactionOverrides): Promise<BigNumber>;

    "name()"(overrides?: TransactionOverrides): Promise<BigNumber>;
  };
}
