/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { EventInterface } from "./EventInterface";

export class EventInterfaceFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EventInterface {
    return new Contract(address, _abi, signerOrProvider) as EventInterface;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "connectorType",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "connectorID",
        type: "uint256"
      },
      {
        internalType: "bytes32",
        name: "eventCode",
        type: "bytes32"
      },
      {
        internalType: "bytes",
        name: "eventData",
        type: "bytes"
      }
    ],
    name: "emitEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];
