/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from ".";
import { GelatoHelpers } from "./GelatoHelpers";

export class GelatoHelpersFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: TransactionOverrides): Promise<GelatoHelpers> {
    return super.deploy(overrides) as Promise<GelatoHelpers>;
  }
  getDeployTransaction(overrides?: TransactionOverrides): UnsignedTransaction {
    return super.getDeployTransaction(overrides);
  }
  attach(address: string): GelatoHelpers {
    return super.attach(address) as GelatoHelpers;
  }
  connect(signer: Signer): GelatoHelpersFactory {
    return super.connect(signer) as GelatoHelpersFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GelatoHelpers {
    return new Contract(address, _abi, signerOrProvider) as GelatoHelpers;
  }
}

const _abi = [
  {
    inputs: [],
    name: "connectorID",
    outputs: [
      {
        internalType: "uint256",
        name: "_type",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256"
      }
    ],
    stateMutability: "pure",
    type: "function"
  }
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060948061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063eb15f78114602d575b600080fd5b60336048565b604051603f9291906050565b60405180910390f35b600190602a90565b91825260208201526040019056fea2646970667358221220a348b409cf8b9a47e1b1a8e3c5266cf7c0bfcd662a94157d2d920536f471121264736f6c634300060c0033";
