/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface GelatoHelpersInterface extends Interface {
  functions: {
    connectorID: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class GelatoHelpers extends Contract {
  connect(signerOrProvider: Signer | Provider | string): GelatoHelpers;
  attach(addressOrName: string): GelatoHelpers;
  deployed(): Promise<GelatoHelpers>;

  on(event: EventFilter | string, listener: Listener): GelatoHelpers;
  once(event: EventFilter | string, listener: Listener): GelatoHelpers;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): GelatoHelpers;
  removeAllListeners(eventName: EventFilter | string): GelatoHelpers;
  removeListener(eventName: any, listener: Listener): GelatoHelpers;

  interface: GelatoHelpersInterface;

  functions: {
    connectorID(
      overrides?: TransactionOverrides
    ): Promise<{
      _type: BigNumber;
      _id: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    "connectorID()"(
      overrides?: TransactionOverrides
    ): Promise<{
      _type: BigNumber;
      _id: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;
  };

  connectorID(
    overrides?: TransactionOverrides
  ): Promise<{
    _type: BigNumber;
    _id: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  "connectorID()"(
    overrides?: TransactionOverrides
  ): Promise<{
    _type: BigNumber;
    _id: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  filters: {};

  estimate: {
    connectorID(overrides?: TransactionOverrides): Promise<BigNumber>;

    "connectorID()"(overrides?: TransactionOverrides): Promise<BigNumber>;
  };
}
