/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface HelpersInterface extends Interface {
  functions: {
    connectorID: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class Helpers extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Helpers;
  attach(addressOrName: string): Helpers;
  deployed(): Promise<Helpers>;

  on(event: EventFilter | string, listener: Listener): Helpers;
  once(event: EventFilter | string, listener: Listener): Helpers;
  addListener(eventName: EventFilter | string, listener: Listener): Helpers;
  removeAllListeners(eventName: EventFilter | string): Helpers;
  removeListener(eventName: any, listener: Listener): Helpers;

  interface: HelpersInterface;

  functions: {
    connectorID(
      overrides?: TransactionOverrides
    ): Promise<{
      _type: BigNumber;
      _id: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    "connectorID()"(
      overrides?: TransactionOverrides
    ): Promise<{
      _type: BigNumber;
      _id: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;
  };

  connectorID(
    overrides?: TransactionOverrides
  ): Promise<{
    _type: BigNumber;
    _id: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  "connectorID()"(
    overrides?: TransactionOverrides
  ): Promise<{
    _type: BigNumber;
    _id: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  filters: {};

  estimate: {
    connectorID(overrides?: TransactionOverrides): Promise<BigNumber>;

    "connectorID()"(overrides?: TransactionOverrides): Promise<BigNumber>;
  };
}
