/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IGelatoProviderModuleInterface extends Interface {
  functions: {
    execPayload: TypedFunctionDescription<{
      encode([_taskReceiptId, _userProxy, _provider, _task, _cycleId]: [
        BigNumberish,
        string,
        string,
        {
          conditions: { inst: string; data: Arrayish }[];
          actions: {
            addr: string;
            data: Arrayish;
            operation: BigNumberish;
            dataFlow: BigNumberish;
            value: BigNumberish;
            termsOkCheck: boolean;
          }[];
          selfProviderGasLimit: BigNumberish;
          selfProviderGasPriceCeil: BigNumberish;
        },
        BigNumberish
      ]): string;
    }>;

    execRevertCheck: TypedFunctionDescription<{
      encode([_proxyReturndata]: [Arrayish]): string;
    }>;

    isProvided: TypedFunctionDescription<{
      encode([_userProxy, _provider, _task]: [
        string,
        string,
        {
          conditions: { inst: string; data: Arrayish }[];
          actions: {
            addr: string;
            data: Arrayish;
            operation: BigNumberish;
            dataFlow: BigNumberish;
            value: BigNumberish;
            termsOkCheck: boolean;
          }[];
          selfProviderGasLimit: BigNumberish;
          selfProviderGasPriceCeil: BigNumberish;
        }
      ]): string;
    }>;
  };

  events: {};
}

export class IGelatoProviderModule extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IGelatoProviderModule;
  attach(addressOrName: string): IGelatoProviderModule;
  deployed(): Promise<IGelatoProviderModule>;

  on(event: EventFilter | string, listener: Listener): IGelatoProviderModule;
  once(event: EventFilter | string, listener: Listener): IGelatoProviderModule;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IGelatoProviderModule;
  removeAllListeners(eventName: EventFilter | string): IGelatoProviderModule;
  removeListener(eventName: any, listener: Listener): IGelatoProviderModule;

  interface: IGelatoProviderModuleInterface;

  functions: {
    execPayload(
      _taskReceiptId: BigNumberish,
      _userProxy: string,
      _provider: string,
      _task: {
        conditions: { inst: string; data: Arrayish }[];
        actions: {
          addr: string;
          data: Arrayish;
          operation: BigNumberish;
          dataFlow: BigNumberish;
          value: BigNumberish;
          termsOkCheck: boolean;
        }[];
        selfProviderGasLimit: BigNumberish;
        selfProviderGasPriceCeil: BigNumberish;
      },
      _cycleId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<{
      checkReturndata: boolean;
      0: string;
      1: boolean;
    }>;

    "execPayload(uint256,address,address,tuple,uint256)"(
      _taskReceiptId: BigNumberish,
      _userProxy: string,
      _provider: string,
      _task: {
        conditions: { inst: string; data: Arrayish }[];
        actions: {
          addr: string;
          data: Arrayish;
          operation: BigNumberish;
          dataFlow: BigNumberish;
          value: BigNumberish;
          termsOkCheck: boolean;
        }[];
        selfProviderGasLimit: BigNumberish;
        selfProviderGasPriceCeil: BigNumberish;
      },
      _cycleId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<{
      checkReturndata: boolean;
      0: string;
      1: boolean;
    }>;

    execRevertCheck(
      _proxyReturndata: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<void>;

    "execRevertCheck(bytes)"(
      _proxyReturndata: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<void>;

    isProvided(
      _userProxy: string,
      _provider: string,
      _task: {
        conditions: { inst: string; data: Arrayish }[];
        actions: {
          addr: string;
          data: Arrayish;
          operation: BigNumberish;
          dataFlow: BigNumberish;
          value: BigNumberish;
          termsOkCheck: boolean;
        }[];
        selfProviderGasLimit: BigNumberish;
        selfProviderGasPriceCeil: BigNumberish;
      },
      overrides?: TransactionOverrides
    ): Promise<string>;

    "isProvided(address,address,tuple)"(
      _userProxy: string,
      _provider: string,
      _task: {
        conditions: { inst: string; data: Arrayish }[];
        actions: {
          addr: string;
          data: Arrayish;
          operation: BigNumberish;
          dataFlow: BigNumberish;
          value: BigNumberish;
          termsOkCheck: boolean;
        }[];
        selfProviderGasLimit: BigNumberish;
        selfProviderGasPriceCeil: BigNumberish;
      },
      overrides?: TransactionOverrides
    ): Promise<string>;
  };

  execPayload(
    _taskReceiptId: BigNumberish,
    _userProxy: string,
    _provider: string,
    _task: {
      conditions: { inst: string; data: Arrayish }[];
      actions: {
        addr: string;
        data: Arrayish;
        operation: BigNumberish;
        dataFlow: BigNumberish;
        value: BigNumberish;
        termsOkCheck: boolean;
      }[];
      selfProviderGasLimit: BigNumberish;
      selfProviderGasPriceCeil: BigNumberish;
    },
    _cycleId: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<{
    checkReturndata: boolean;
    0: string;
    1: boolean;
  }>;

  "execPayload(uint256,address,address,tuple,uint256)"(
    _taskReceiptId: BigNumberish,
    _userProxy: string,
    _provider: string,
    _task: {
      conditions: { inst: string; data: Arrayish }[];
      actions: {
        addr: string;
        data: Arrayish;
        operation: BigNumberish;
        dataFlow: BigNumberish;
        value: BigNumberish;
        termsOkCheck: boolean;
      }[];
      selfProviderGasLimit: BigNumberish;
      selfProviderGasPriceCeil: BigNumberish;
    },
    _cycleId: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<{
    checkReturndata: boolean;
    0: string;
    1: boolean;
  }>;

  execRevertCheck(
    _proxyReturndata: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<void>;

  "execRevertCheck(bytes)"(
    _proxyReturndata: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<void>;

  isProvided(
    _userProxy: string,
    _provider: string,
    _task: {
      conditions: { inst: string; data: Arrayish }[];
      actions: {
        addr: string;
        data: Arrayish;
        operation: BigNumberish;
        dataFlow: BigNumberish;
        value: BigNumberish;
        termsOkCheck: boolean;
      }[];
      selfProviderGasLimit: BigNumberish;
      selfProviderGasPriceCeil: BigNumberish;
    },
    overrides?: TransactionOverrides
  ): Promise<string>;

  "isProvided(address,address,tuple)"(
    _userProxy: string,
    _provider: string,
    _task: {
      conditions: { inst: string; data: Arrayish }[];
      actions: {
        addr: string;
        data: Arrayish;
        operation: BigNumberish;
        dataFlow: BigNumberish;
        value: BigNumberish;
        termsOkCheck: boolean;
      }[];
      selfProviderGasLimit: BigNumberish;
      selfProviderGasPriceCeil: BigNumberish;
    },
    overrides?: TransactionOverrides
  ): Promise<string>;

  filters: {};

  estimate: {
    execPayload(
      _taskReceiptId: BigNumberish,
      _userProxy: string,
      _provider: string,
      _task: {
        conditions: { inst: string; data: Arrayish }[];
        actions: {
          addr: string;
          data: Arrayish;
          operation: BigNumberish;
          dataFlow: BigNumberish;
          value: BigNumberish;
          termsOkCheck: boolean;
        }[];
        selfProviderGasLimit: BigNumberish;
        selfProviderGasPriceCeil: BigNumberish;
      },
      _cycleId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "execPayload(uint256,address,address,tuple,uint256)"(
      _taskReceiptId: BigNumberish,
      _userProxy: string,
      _provider: string,
      _task: {
        conditions: { inst: string; data: Arrayish }[];
        actions: {
          addr: string;
          data: Arrayish;
          operation: BigNumberish;
          dataFlow: BigNumberish;
          value: BigNumberish;
          termsOkCheck: boolean;
        }[];
        selfProviderGasLimit: BigNumberish;
        selfProviderGasPriceCeil: BigNumberish;
      },
      _cycleId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    execRevertCheck(
      _proxyReturndata: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "execRevertCheck(bytes)"(
      _proxyReturndata: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    isProvided(
      _userProxy: string,
      _provider: string,
      _task: {
        conditions: { inst: string; data: Arrayish }[];
        actions: {
          addr: string;
          data: Arrayish;
          operation: BigNumberish;
          dataFlow: BigNumberish;
          value: BigNumberish;
          termsOkCheck: boolean;
        }[];
        selfProviderGasLimit: BigNumberish;
        selfProviderGasPriceCeil: BigNumberish;
      },
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "isProvided(address,address,tuple)"(
      _userProxy: string,
      _provider: string,
      _task: {
        conditions: { inst: string; data: Arrayish }[];
        actions: {
          addr: string;
          data: Arrayish;
          operation: BigNumberish;
          dataFlow: BigNumberish;
          value: BigNumberish;
          termsOkCheck: boolean;
        }[];
        selfProviderGasLimit: BigNumberish;
        selfProviderGasPriceCeil: BigNumberish;
      },
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;
  };
}
