/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IGelatoInterface } from "./IGelatoInterface";

export class IGelatoInterfaceFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGelatoInterface {
    return new Contract(address, _abi, signerOrProvider) as IGelatoInterface;
  }
}

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256"
          },
          {
            internalType: "address",
            name: "userProxy",
            type: "address"
          },
          {
            components: [
              {
                internalType: "address",
                name: "addr",
                type: "address"
              },
              {
                internalType: "address",
                name: "module",
                type: "address"
              }
            ],
            internalType: "struct Provider",
            name: "provider",
            type: "tuple"
          },
          {
            internalType: "uint256",
            name: "index",
            type: "uint256"
          },
          {
            components: [
              {
                components: [
                  {
                    internalType: "address",
                    name: "inst",
                    type: "address"
                  },
                  {
                    internalType: "bytes",
                    name: "data",
                    type: "bytes"
                  }
                ],
                internalType: "struct Condition[]",
                name: "conditions",
                type: "tuple[]"
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "addr",
                    type: "address"
                  },
                  {
                    internalType: "bytes",
                    name: "data",
                    type: "bytes"
                  },
                  {
                    internalType: "enum Operation",
                    name: "operation",
                    type: "uint8"
                  },
                  {
                    internalType: "enum DataFlow",
                    name: "dataFlow",
                    type: "uint8"
                  },
                  {
                    internalType: "uint256",
                    name: "value",
                    type: "uint256"
                  },
                  {
                    internalType: "bool",
                    name: "termsOkCheck",
                    type: "bool"
                  }
                ],
                internalType: "struct Action[]",
                name: "actions",
                type: "tuple[]"
              },
              {
                internalType: "uint256",
                name: "selfProviderGasLimit",
                type: "uint256"
              },
              {
                internalType: "uint256",
                name: "selfProviderGasPriceCeil",
                type: "uint256"
              }
            ],
            internalType: "struct Task[]",
            name: "tasks",
            type: "tuple[]"
          },
          {
            internalType: "uint256",
            name: "expiryDate",
            type: "uint256"
          },
          {
            internalType: "uint256",
            name: "cycleId",
            type: "uint256"
          },
          {
            internalType: "uint256",
            name: "submissionsLeft",
            type: "uint256"
          }
        ],
        internalType: "struct TaskReceipt[]",
        name: "_taskReceipts",
        type: "tuple[]"
      }
    ],
    name: "multiCancelTasks",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_executor",
        type: "address"
      },
      {
        components: [
          {
            internalType: "address[]",
            name: "conditions",
            type: "address[]"
          },
          {
            components: [
              {
                internalType: "address",
                name: "addr",
                type: "address"
              },
              {
                internalType: "bytes",
                name: "data",
                type: "bytes"
              },
              {
                internalType: "enum Operation",
                name: "operation",
                type: "uint8"
              },
              {
                internalType: "enum DataFlow",
                name: "dataFlow",
                type: "uint8"
              },
              {
                internalType: "uint256",
                name: "value",
                type: "uint256"
              },
              {
                internalType: "bool",
                name: "termsOkCheck",
                type: "bool"
              }
            ],
            internalType: "struct Action[]",
            name: "actions",
            type: "tuple[]"
          },
          {
            internalType: "uint256",
            name: "gasPriceCeil",
            type: "uint256"
          }
        ],
        internalType: "struct TaskSpec[]",
        name: "_taskSpecs",
        type: "tuple[]"
      },
      {
        internalType: "address[]",
        name: "_modules",
        type: "address[]"
      }
    ],
    name: "multiProvide",
    outputs: [],
    stateMutability: "payable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_withdrawAmount",
        type: "uint256"
      },
      {
        components: [
          {
            internalType: "address[]",
            name: "conditions",
            type: "address[]"
          },
          {
            components: [
              {
                internalType: "address",
                name: "addr",
                type: "address"
              },
              {
                internalType: "bytes",
                name: "data",
                type: "bytes"
              },
              {
                internalType: "enum Operation",
                name: "operation",
                type: "uint8"
              },
              {
                internalType: "enum DataFlow",
                name: "dataFlow",
                type: "uint8"
              },
              {
                internalType: "uint256",
                name: "value",
                type: "uint256"
              },
              {
                internalType: "bool",
                name: "termsOkCheck",
                type: "bool"
              }
            ],
            internalType: "struct Action[]",
            name: "actions",
            type: "tuple[]"
          },
          {
            internalType: "uint256",
            name: "gasPriceCeil",
            type: "uint256"
          }
        ],
        internalType: "struct TaskSpec[]",
        name: "_taskSpecs",
        type: "tuple[]"
      },
      {
        internalType: "address[]",
        name: "_modules",
        type: "address[]"
      }
    ],
    name: "multiUnprovide",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "addr",
            type: "address"
          },
          {
            internalType: "address",
            name: "module",
            type: "address"
          }
        ],
        internalType: "struct Provider",
        name: "_provider",
        type: "tuple"
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "inst",
                type: "address"
              },
              {
                internalType: "bytes",
                name: "data",
                type: "bytes"
              }
            ],
            internalType: "struct Condition[]",
            name: "conditions",
            type: "tuple[]"
          },
          {
            components: [
              {
                internalType: "address",
                name: "addr",
                type: "address"
              },
              {
                internalType: "bytes",
                name: "data",
                type: "bytes"
              },
              {
                internalType: "enum Operation",
                name: "operation",
                type: "uint8"
              },
              {
                internalType: "enum DataFlow",
                name: "dataFlow",
                type: "uint8"
              },
              {
                internalType: "uint256",
                name: "value",
                type: "uint256"
              },
              {
                internalType: "bool",
                name: "termsOkCheck",
                type: "bool"
              }
            ],
            internalType: "struct Action[]",
            name: "actions",
            type: "tuple[]"
          },
          {
            internalType: "uint256",
            name: "selfProviderGasLimit",
            type: "uint256"
          },
          {
            internalType: "uint256",
            name: "selfProviderGasPriceCeil",
            type: "uint256"
          }
        ],
        internalType: "struct Task",
        name: "_task",
        type: "tuple"
      },
      {
        internalType: "uint256",
        name: "_expiryDate",
        type: "uint256"
      }
    ],
    name: "submitTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "addr",
            type: "address"
          },
          {
            internalType: "address",
            name: "module",
            type: "address"
          }
        ],
        internalType: "struct Provider",
        name: "_provider",
        type: "tuple"
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "inst",
                type: "address"
              },
              {
                internalType: "bytes",
                name: "data",
                type: "bytes"
              }
            ],
            internalType: "struct Condition[]",
            name: "conditions",
            type: "tuple[]"
          },
          {
            components: [
              {
                internalType: "address",
                name: "addr",
                type: "address"
              },
              {
                internalType: "bytes",
                name: "data",
                type: "bytes"
              },
              {
                internalType: "enum Operation",
                name: "operation",
                type: "uint8"
              },
              {
                internalType: "enum DataFlow",
                name: "dataFlow",
                type: "uint8"
              },
              {
                internalType: "uint256",
                name: "value",
                type: "uint256"
              },
              {
                internalType: "bool",
                name: "termsOkCheck",
                type: "bool"
              }
            ],
            internalType: "struct Action[]",
            name: "actions",
            type: "tuple[]"
          },
          {
            internalType: "uint256",
            name: "selfProviderGasLimit",
            type: "uint256"
          },
          {
            internalType: "uint256",
            name: "selfProviderGasPriceCeil",
            type: "uint256"
          }
        ],
        internalType: "struct Task[]",
        name: "_tasks",
        type: "tuple[]"
      },
      {
        internalType: "uint256",
        name: "_expiryDate",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "_sumOfRequestedTaskSubmits",
        type: "uint256"
      }
    ],
    name: "submitTaskChain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "addr",
            type: "address"
          },
          {
            internalType: "address",
            name: "module",
            type: "address"
          }
        ],
        internalType: "struct Provider",
        name: "_provider",
        type: "tuple"
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "inst",
                type: "address"
              },
              {
                internalType: "bytes",
                name: "data",
                type: "bytes"
              }
            ],
            internalType: "struct Condition[]",
            name: "conditions",
            type: "tuple[]"
          },
          {
            components: [
              {
                internalType: "address",
                name: "addr",
                type: "address"
              },
              {
                internalType: "bytes",
                name: "data",
                type: "bytes"
              },
              {
                internalType: "enum Operation",
                name: "operation",
                type: "uint8"
              },
              {
                internalType: "enum DataFlow",
                name: "dataFlow",
                type: "uint8"
              },
              {
                internalType: "uint256",
                name: "value",
                type: "uint256"
              },
              {
                internalType: "bool",
                name: "termsOkCheck",
                type: "bool"
              }
            ],
            internalType: "struct Action[]",
            name: "actions",
            type: "tuple[]"
          },
          {
            internalType: "uint256",
            name: "selfProviderGasLimit",
            type: "uint256"
          },
          {
            internalType: "uint256",
            name: "selfProviderGasPriceCeil",
            type: "uint256"
          }
        ],
        internalType: "struct Task[]",
        name: "_tasks",
        type: "tuple[]"
      },
      {
        internalType: "uint256",
        name: "_expiryDate",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "_cycles",
        type: "uint256"
      }
    ],
    name: "submitTaskCycle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];
