/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IndexInterface } from "./IndexInterface";

export class IndexInterfaceFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IndexInterface {
    return new Contract(address, _abi, signerOrProvider) as IndexInterface;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "version",
        type: "uint256"
      }
    ],
    name: "connectors",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [],
    name: "list",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
