/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IndexInterfaceInterface extends Interface {
  functions: {
    connectors: TypedFunctionDescription<{
      encode([version]: [BigNumberish]): string;
    }>;

    list: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class IndexInterface extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IndexInterface;
  attach(addressOrName: string): IndexInterface;
  deployed(): Promise<IndexInterface>;

  on(event: EventFilter | string, listener: Listener): IndexInterface;
  once(event: EventFilter | string, listener: Listener): IndexInterface;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IndexInterface;
  removeAllListeners(eventName: EventFilter | string): IndexInterface;
  removeListener(eventName: any, listener: Listener): IndexInterface;

  interface: IndexInterfaceInterface;

  functions: {
    connectors(
      version: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "connectors(uint256)"(
      version: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    list(overrides?: TransactionOverrides): Promise<string>;

    "list()"(overrides?: TransactionOverrides): Promise<string>;
  };

  connectors(
    version: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "connectors(uint256)"(
    version: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  list(overrides?: TransactionOverrides): Promise<string>;

  "list()"(overrides?: TransactionOverrides): Promise<string>;

  filters: {};

  estimate: {
    connectors(
      version: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "connectors(uint256)"(
      version: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    list(overrides?: TransactionOverrides): Promise<BigNumber>;

    "list()"(overrides?: TransactionOverrides): Promise<BigNumber>;
  };
}
