/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { MemoryInterface } from "./MemoryInterface";

export class MemoryInterfaceFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MemoryInterface {
    return new Contract(address, _abi, signerOrProvider) as MemoryInterface;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256"
      }
    ],
    name: "getUint",
    outputs: [
      {
        internalType: "uint256",
        name: "num",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "val",
        type: "uint256"
      }
    ],
    name: "setUint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];
