/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface MockDsrInterface extends Interface {
  functions: {
    dsr: TypedFunctionDescription<{ encode([]: []): string }>;

    setDSR: TypedFunctionDescription<{
      encode([_dsr]: [BigNumberish]): string;
    }>;
  };

  events: {};
}

export class MockDsr extends Contract {
  connect(signerOrProvider: Signer | Provider | string): MockDsr;
  attach(addressOrName: string): MockDsr;
  deployed(): Promise<MockDsr>;

  on(event: EventFilter | string, listener: Listener): MockDsr;
  once(event: EventFilter | string, listener: Listener): MockDsr;
  addListener(eventName: EventFilter | string, listener: Listener): MockDsr;
  removeAllListeners(eventName: EventFilter | string): MockDsr;
  removeListener(eventName: any, listener: Listener): MockDsr;

  interface: MockDsrInterface;

  functions: {
    dsr(overrides?: TransactionOverrides): Promise<BigNumber>;

    "dsr()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    setDSR(
      _dsr: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "setDSR(uint256)"(
      _dsr: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  dsr(overrides?: TransactionOverrides): Promise<BigNumber>;

  "dsr()"(overrides?: TransactionOverrides): Promise<BigNumber>;

  setDSR(
    _dsr: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "setDSR(uint256)"(
    _dsr: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    dsr(overrides?: TransactionOverrides): Promise<BigNumber>;

    "dsr()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    setDSR(
      _dsr: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "setDSR(uint256)"(
      _dsr: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;
  };
}
