/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";
import { BigNumberish } from "ethers/utils";

import { TransactionOverrides } from ".";
import { MockDsr } from "./MockDsr";

export class MockDsrFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _dsr: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<MockDsr> {
    return super.deploy(_dsr, overrides) as Promise<MockDsr>;
  }
  getDeployTransaction(
    _dsr: BigNumberish,
    overrides?: TransactionOverrides
  ): UnsignedTransaction {
    return super.getDeployTransaction(_dsr, overrides);
  }
  attach(address: string): MockDsr {
    return super.attach(address) as MockDsr;
  }
  connect(signer: Signer): MockDsrFactory {
    return super.connect(signer) as MockDsrFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockDsr {
    return new Contract(address, _abi, signerOrProvider) as MockDsr;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_dsr",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "constructor"
  },
  {
    inputs: [],
    name: "dsr",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_dsr",
        type: "uint256"
      }
    ],
    name: "setDSR",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516100f23803806100f28339818101604052602081101561003357600080fd5b505160005560ac806100466000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c8063487bf08214603757806365c0ac4b14604f575b600080fd5b603d606b565b60408051918252519081900360200190f35b606960048036036020811015606357600080fd5b50356071565b005b60005481565b60005556fea26469706673582212202f6cf2a51019dae84de7fbcade14d5b0c134c190099d4666dfb53b86edeefacb64736f6c634300060c0033";
